REQUIREMENTS=[
                "deltalake",
                "pandas",
                "pyarrow",
                "futures", 
                "requests",
                "duckdb",
                "retry",
                "Office365-REST-Python-Client==2.5.12",
                "openpyxl",
                "boto3"
            ]