dags:
  - name: a_example_dag_1
    schedule_interval: "0 12 * * *"
    default_args:
      owner: k.melnikov
      email_on_retry: True
      email:
        - k.melnikov@temabit.com
      depends_on_past: False
    tags:
      - stores_sales
    params:
        details: 1
        input:
          sharepoint_chanel: CyberSecurity
          sharepoint_folder_name: check_list
          sharepoint_file_name: Security Check List_results_.xlsx
        output:
          minio_bucket: kru-readonly
          minio_path: sharepoint/chanel_name/table_name
