dags:
  - name: _example_dag____1
    schedule_interval: "0 12 * * *"
    default_args:
      owner: k.melnikov
      email_on_retry: True
      email: 
        - k.melnikov@temabit.com
      depends_on_past: False
    tags: 
      - <task_name>
    tasks:
      - task_id: task_load_1
        type: load
        params:
          minio_bucket: <teamname>-readonly
          minio_path: sharepoint/chanel_name/table_name
          sharepoint_chanel: CyberSecurity
          sharepoint_folder_name: check_list
          sharepoint_file_name: Security Check List_results_.xlsx
      - task_id: task_optimmize_2
        type: optimize
        params:
          minio_bucket: dgoit-readonly
          minio_path: sharepoint/chanel_name/table_name

  - name: _example_dag____2
    schedule_interval: "0 12 * * *"
    default_args:
      owner: k.melnikov
      email_on_retry: True
      email: 
        - k.melnikov@temabit.com
      depends_on_past: False
    tags: 
      - <task_name>
    tasks:
      - task_id: task_bash_3
        type: bash
        params:
          minio_bucket: <teamname>-readonly
          minio_path: sharepoint/chanel_name/table_name
          sharepoint_chanel: CyberSecurity
          sharepoint_folder_name: check_list
          sharepoint_file_name: Security Check List_results_.xlsx 