REQUIREMENTS=[
                "deltalake==0.19.1", 
                "pandas==2.2.0", 
                "pyarrow==17.0.0",  
                "futures", 
                "requests==2.31.0",
                "duckdb==1.0.0",
                "retry",
                "Office365-REST-Python-Client==2.5.12",
                "openpyxl"
            ]